---
- name: Setup local environment
  hosts: local

  pre_tasks:

    - name: Ping
      ansible.builtin.ping:

  roles:
    - role: archlinux-base
      tags:
        - base

  # handlers:
  #   - include: common/handlers/main.yml
