server {
    include snippets/http.conf;
    include snippets/https.conf;
    server_name middleware.vm.local;
    root /home/tung/code/netsuite-middleware/public;
    include snippets/laravel-81.conf;
}