#SPDX-License-Identifier: MIT-0
---
# tasks file for devbox
- name: Ping
  ansible.builtin.ping:

- name: Update package cache
  become: yes
  community.general.pacman:
    update_cache: true

- name: Setup main user
  become: yes
  ansible.builtin.user:
    name: tung
    comment: Test User
    groups:
      - wheel
    create_home: true
    shell: /usr/bin/zsh
    password: "$1$1fiOgY1j$g4DHtZKcAoz0cRrmqqIf31"

- ansible.builtin.include_tasks: archlinux-aur.yml

# Install packages
- name: Install packages
  kewlfft.aur.aur:
    use: paru
    name:
      - git
      - tmux
      - zsh
      - neovim
    state: present

- ansible.builtin.include_tasks: archlinux-php81.yml