---
- name: Install PHP 8.3
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: php83
    use: makepkg
    state: present

- name: Install PHP 8.3 packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: paru
    name:
      - php83-igbinary
      # - php83-imagick
      - php83-memcached
      - php83-redis
      - php83-xdebug
      - php83-apcu
      - php83-mcrypt
    state: present

- name: PHP 8.3 custom config
  become: true
  ansible.builtin.template:
    src: php83/99-custom.ini.j2
    dest: /etc/php83/conf.d/99-custom.ini
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - Restart php83-fpm

- name: Enable & start php83-fpm service
  become: true
  ansible.builtin.systemd_service:
    name: php83-fpm
    state: started
    enabled: true
